### ISSUE TITLE
Networkx error

### ISSUE THREAD

**Issue by whisperxd** [lantip/coronatracking#3]
import networkx as nx
ModuleNotFoundError: No module named 'networkx'

padahal ane udh download modulenya 

pip install networkx[all]
Requirement already satisfied: networkx[all] in /usr/lib/python3/dist-packages (2.5)
Requirement already satisfied: lxml in /usr/lib/python3/dist-packages (from networkx[all]) (4.6.3)
Requirement already satisfied: matplotlib in /usr/lib/python3/dist-packages (from networkx[all]) (3.3.4)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from networkx[all]) (1.19.5)
Requirement already satisfied: pandas in /usr/lib/python3/dist-packages (from networkx[all]) (1.1.5)
Requirement already satisfied: pydot in /usr/lib/python3/dist-packages (from networkx[all]) (1.4.2)
Requirement already satisfied: pygraphviz in /usr/lib/python3/dist-packages (from networkx[all]) (1.7)
Requirement already satisfied: pytest in /usr/lib/python3/dist-packages (from networkx[all]) (6.0.2)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from networkx[all]) (5.3.1)
Requirement already satisfied: scipy in /usr/lib/python3/dist-packages (from networkx[all]) (1.6.0)

**Comment by whisperxd** [comment]
python draw.py -l spring

**Comment by whisperxd** [comment]
cat Pipfile
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
pandas = "/usr/lib/python3/dist-packages/pandas"
ipython = "/home/whisperx/anaconda3/bin/ipython"
networkx = "/usr/lib/python3/dist-packages/networkx"
matplotlib = "/usr/lib/python3/dist-packages/matplotlib"
scipy = "/usr/lib/python3/dist-packages/scipy"
pytesseract = "./.local/lib/python3.9/site-packages/pytesseract"
prettytable = "/usr/lib/python3/dist-packages/prettytable"
requests = "/usr/lib/python3/dist-packages/requests"
beautifulsoup4 = "/usr/lib/python3/dist-packages/beautifulsoup4"
opencv-python = "/home/whisperx/.local/lib/python3.9/site-packages/opencv_python.libs"

[requires]
python_version = "3.9"

**Comment by lantip** [comment]
Halo mas, scriptnya memang saya bikin pakai python 3.7, 
tapi barusan saya coba reproduce di python 3.9 tidak ada masalah.
coba dipull hasil push terakhir saya, lalu  jalankan `pip install -r requirements.txt`

jika muncul segmentation fault, kemungkinan matplotlibnya, silakan jalankan `pip install --upgrade matplotlib`
